name: Build

on:
  push:
  pull_request:
  release:

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: "Install dependencies"
      run: |
       sudo apt update
       sudo apt install libpng-dev libsdl2-dev libsdl2-ttf-dev libtbb-dev libglm-dev libglew-dev libtbb-dev liblua5.3-dev
    - name: "Build"
      run: |
       cmake -DUNIT_TEST=1 -DCMAKE_BUILD_TYPE=Release -DUR_BACKEND_OPENGL=1 .
       make -j$(nproc)
       cp game/game .
       mv game soe
       cp unified_render/libunified_render.so .
       cp unified_render/libunified_render.a .
       make -j
    - name: "Run"
      run: |
        echo "Yay!"
#       ./SymphonyOfEmpires
